#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Apr 24 19:15:14 2016

@author: jamesaxl
"""
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)
from Base.Settings.BarnamySettings import BarnamySettings as BRS

class GuiSettingFirstTime(Gtk.Window):

    def __init__(self):
        self.BarnamyBase = BRS()
        Gtk.Window.__init__(self, title="Barnamy Settings")
        self.connect("delete-event", Gtk.main_quit)
        self.connect("delete-event", self.barnamy_settings_close)
        
        vbox1 = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=7)
        hbox1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
        hbox_ws = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
        vbox_ws = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=1)
        hbox2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=3)

        self.barnamy_ip_entry = Gtk.Entry()
        self.barnamy_port_entry = Gtk.Entry()
        self.barnamy_proxy_entry = Gtk.Entry()

        self.barnamy_ip_entry.set_placeholder_text('IP/URL')
        self.barnamy_port_entry.set_placeholder_text('PORT')
        self.barnamy_proxy_entry.set_placeholder_text('PROXY')

        web_server_expander = Gtk.Expander()
        web_server_expander.set_label('Web Server')
        self.web_server_port = Gtk.Entry()
        self.web_server_action = Gtk.Switch()
        
        web_server_tls = Gtk.Label("TLS")
        self.web_server_tls_action = Gtk.Switch()
        self.web_server_tls_port = Gtk.Entry()
        self.web_server_tls_path = Gtk.Entry()

        sound_expander = Gtk.Expander()
        self.sound_switch = Gtk.Switch()
        self.sound_switch.set_active(False)
        sound_expander.add(self.sound_switch)
        sound_expander.set_label('Sound')

        log_expander = Gtk.Expander()
        self.log_switch = Gtk.Switch()
        self.log_switch.set_active(False)
        log_expander.add(self.log_switch)
        log_expander.set_label('Log')

        notify_expander = Gtk.Expander()
        self.notify_switch = Gtk.Switch()
        self.notify_switch.set_active(False)
        notify_expander.add(self.notify_switch)
        notify_expander.set_label('Notify')

        tls_expander = Gtk.Expander()
        self.tls_switch = Gtk.Switch()
        self.tls_switch.set_active(False)
        tls_expander.add(self.tls_switch)
        tls_expander.set_label('TLS')

        save = Gtk.Button('Save')
        close = Gtk.Button('Close')

        close.connect("clicked", self.barnamy_settings_close)
        save.connect("clicked", self.barnamy_settings_save)

        hbox1.pack_start(self.web_server_port, False, True, 7)
        hbox1.pack_start(self.web_server_action, False, False, 7)
        
        hbox_ws.pack_start(web_server_tls, False, True, 7)
        hbox_ws.pack_start(self.web_server_tls_port, False, True, 7)
        hbox_ws.pack_start(self.web_server_tls_action, False, True, 7)
        hbox_ws.pack_start(self.web_server_tls_path, False, True, 7)

        vbox_ws.pack_start(hbox1, False, True, 0)
        vbox_ws.pack_start(hbox_ws, False, True, 0)

        hbox2.pack_end(save, False, True, 7)
        hbox2.pack_end(close, False, False, 7)
        web_server_expander.add(vbox_ws)

        vbox1.pack_start(self.barnamy_ip_entry, False, True, 0)
        vbox1.pack_start(self.barnamy_port_entry, False, True, 0)
        vbox1.pack_start(self.barnamy_proxy_entry, False, True, 0)
        vbox1.pack_start(web_server_expander, False, True, 0)
        vbox1.pack_start(sound_expander, False, True, 0)
        vbox1.pack_start(log_expander, False, True, 0)
        vbox1.pack_start(notify_expander, False, True, 0)
        vbox1.pack_start(tls_expander, False, True, 0)
        vbox1.pack_end(hbox2, False, True, 0)
        vbox1.set_border_width(10)
        self.add(vbox1)

    def barnamy_settings_close(self, widget, event = 0):
        self.close()

    def barnamy_settings_open(self):
        settings = self.BarnamyBase.get_settings()
        self.barnamy_ip_entry.set_text(settings['ip'])
        self.barnamy_port_entry.set_text(str(settings['port']))
        self.web_server_port.set_text(str(settings['wport']))
        self.web_server_tls_action.set_active(settings['web_tls'])
        self.web_server_tls_port.set_text(str(settings['web_tls_port']))
        self.web_server_tls_path.set_text(settings['web_tls_path'])
        self.sound_switch.set_active(settings['sound'])
        self.notify_switch.set_active(settings['notify'])
        self.log_switch.set_active(settings['log'])
        self.tls_switch.set_active(settings['tls'])
        self.show_all()

    def barnamy_settings_save(self, widget):
        data = {'ip' : self.barnamy_ip_entry.get_text(), 'port' : self.barnamy_port_entry.get_text(), 
                'wport' : self.web_server_port.get_text(), 'web_tls' : self.web_server_tls_action.get_active(), 
                'web_tls_port' : self.web_server_tls_port.get_text(), 'web_tls_path' : self.web_server_tls_path.get_text(),
                'sound' : self.sound_switch.get_active(), 'notify' : self.notify_switch.get_active(), 
                'log' : self.log_switch.get_active(), 'tls' : self.tls_switch.get_active()}
        self.BarnamyBase.save_settings(data)

bsft = GuiSettingFirstTime()
bsft.barnamy_settings_open()
Gtk.main()
