#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
from Base.Settings.BarnamySettings import BarnamySettings as BRS

class GuiSettingFirstTime(object):
    def __init__(self):
        self.barnamy_widget = {}
        self.settings = BRS()
        self._builder = Gtk.Builder()
        self._builder.add_from_file("Theme/GuiGtk/barnamy_ui.glade")
        self.barnamy_widget["baramy_settings"] = self._builder.get_object("baramy_settings")
        self.barnamy_widget["bt_save_settings"] = self._builder.get_object("bt_save_settings")
        self.barnamy_widget["bt_close_setting"] = self._builder.get_object("bt_close_setting")
        self.barnamy_widget['entry_ip']  = self._builder.get_object("entry_ip")
        self.barnamy_widget['entry_port'] = self._builder.get_object("entry_port")
        self.barnamy_widget['switch_sound'] = self._builder.get_object("switch_sound")
        self.barnamy_widget['switch_notify'] = self._builder.get_object("switch_notify")
        self.barnamy_widget['switch_log'] = self._builder.get_object("switch_log")
        self.barnamy_widget["switch_tls"] = self._builder.get_object("switch_tls")

        self.barnamy_widget["bt_close_setting"].connect("clicked", self.barnamy_settings_close)
        self.barnamy_widget["baramy_settings"].connect("delete-event", self.barnamy_settings_close)
        self.barnamy_widget["bt_save_settings"].connect("clicked", self.barnamy_save_setting)

    def barnamy_settings_open(self):
        self.barnamy_widget["baramy_settings"].show_all()
        settings = self.settings.get_settings()
        self.barnamy_widget['entry_ip'].set_text(settings['ip'])
        self.barnamy_widget['entry_port'].set_text(str(settings['port']))
        self.barnamy_widget['switch_sound'].set_active(settings['sound'])
        self.barnamy_widget['switch_notify'].set_active(settings['notify'])
        self.barnamy_widget['switch_log'].set_active(settings['log'])
        self.barnamy_widget["switch_tls"].set_active(settings['tls'])

    def barnamy_settings_close(self, widget = 0, event = 0):
        self.barnamy_widget["baramy_settings"].close()
        Gtk.main_quit()
        

    def barnamy_save_setting(self, widget):
        settings = {"ip":self.barnamy_widget["entry_ip"].get_text(), "port":self.barnamy_widget["entry_port"].get_text(), 
                    "sound":self.barnamy_widget["switch_sound"].get_active(), "notify":self.barnamy_widget["switch_notify"].get_active(),
                    "log":self.barnamy_widget["switch_log"].get_active(), "tls":self.barnamy_widget["switch_tls"].get_active()}

        self.settings.save_settings(settings)
        self.barnamy_settings_close()

bsft = GuiSettingFirstTime()
bsft.barnamy_settings_open()
Gtk.main()
